module.exports = {
  apps: [
    {
      name: "blog-generator-api",
      script: "main.py",
      interpreter: "python3",
      cwd: "/home/ubuntu/Blog_generator/blogwriter_CrewAi",
      env: {
        NODE_ENV: "production",
        RUN_MODE: "api",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      log_file: "./logs/api-combined.log",
      time: true,
      merge_logs: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "blog-generator-standalone",
      script: "main.py",
      interpreter: "python3",
      cwd: "/home/ubuntu/Blog_generator/blogwriter_CrewAi",
      env: {
        RUN_MODE: "standalone",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/standalone-error.log",
      out_file: "./logs/standalone-out.log",
      log_file: "./logs/standalone-combined.log",
      time: true,
      merge_logs: true,
      kill_timeout: 5000,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
    },
  ],
};
